GET http://localhost:5292/

###
GET http://localhost:5292/api/pet

###
GET http://localhost:5292/api/pet/1

###
POST http://localhost:5292/api/pet
Content-Type: application/json

{
    "name": "Bonbon",
    "nickname": "Bonny",
    "gender": "Male",
    "speciesId": 1,
    "speciesName": "Dog",
    "birthDate": "2016-11-12",
    "breed": "Labrador",
    "weight": 25,
    "color": "Yellow",
    "imageName": "bonbon.jpg",
    "imagePath": "wwwroot/images/bonbon.jpg"
}

###
PUT http://localhost:5292/api/pet/1
Content-Type: application/json

{
    "id": 2,
    "name": "Woi",
    "nickname": "Woiie",
    "gender": "Female",
    "speciesId": 2,
    "speciesName": "Cat",
    "birthDate": "2012-12-12",
    "breed": "Beagle",
    "weight": 20,
    "color": "Brown",
    "imageName": "woi.jpg",
    "imagePath": "wwwroot/images/woi.jpg"
}

###
DELETE http://localhost:5292/api/pet/3

###
GET http://localhost:5292/api/species